name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '17', '21', '23-ea' ]

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        show-progress: false

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: ./gradlew build
      run: ./gradlew build
    - name: ./gradlew javadoc
      run: ./gradlew javadoc
    - name: ./gradlew requireJavadoc
      run: ./gradlew requireJavadoc
    - name: ./gradlew spotlessCheck
      run: ./gradlew spotlessCheck
